#  lutron-sunnata-keypad-click-long-click-double-click.yaml- handle click, long press/release, and double-click events from a Lutron Sunnata keypad
#  Copyright 2026 Benjamin ENgber
#
#   Licensed under the Apache License, Version 2.0 (the "License");
#   you may not use this file except in compliance with the License.
#   You may obtain a copy of the License at
#
#       http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing, software
#   distributed under the License is distributed on an "AS IS" BASIS,
#   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
#   See the License for the specific language governing permissions and
#   limitations under the License.

blueprint:
  name: Lutron Sunnata Keypad Click/Long Click/Double Click
  description: >
    Advanced button press detection for Lutron Sunnata keypads supporting
    single click, double click, and long press actions for each button.
    
    
    Single click events will fire immediately if long press and double click are not defined.


    **NOTE:** In order to use the long press and double click handlers for buttons other than Raise/Lower, 
    the button behavior needs to be set as ***Sinngle Action*** in the Lutron designer software. 
    (Using either ***Scene Toggle*** or ***Zone Toggle*** will prevent the button release events from being fired.)
  domain: automation
  home_assistant:
    min_version: 2024.6.0
  input:
    sunnata_keypad:
      name: Sunnata Keypad
      description: The Lutron Sunnata keypad to control
      selector:
        device:
          filter:
            - integration: lutron_caseta
              model: RRST-W2B-XX (SunnataKeypad)
            - integration: lutron_caseta
              model: RRST-HN2B-XX (SunnataHybridKeypad)
            - integration: lutron_caseta
              model: RRST-W3RL-XX (SunnataKeypad)
            - integration: lutron_caseta
              model: RRST-HN3RL-XX (SunnataHybridKeypad)
            - integration: lutron_caseta
              model: RRST-W4B-XX (SunnataKeypad)
            - integration: lutron_caseta
              model: RRST-HN4B-XX (SunnataHybridKeypad)
          multiple: false
    
    button_1_group:
      name: "Button 1 (Top Button) Actions"
      icon: mdi:numeric-1-box
      collapsed: true
      input:
        button_1_single_click:
          name: Single Click Action
          description: Action to perform on single click of button 1
          default: []
          selector:
            action: {}
        button_1_double_click:
          name: Double Click Action
          description: Action to perform on double click of button 1 (leave empty to disable double-click detection)
          default: []
          selector:
            action: {}
        button_1_long_press:
          name: Long Press Action
          description: Action to perform on long press of button 1 (leave empty to disable long-press detection)
          default: []
          selector:
            action: {}
        button_1_release:
          name: Release After Long Press Action
          description: Action to perform when button 1 is released after a long press
          default: []
          selector:
            action: {}

    button_2_group:
      name: "Button 2 Actions"
      icon: mdi:numeric-2-box
      collapsed: true
      input:
        button_2_single_click:
          name: Single Click Action
          description: Action to perform on single click of button 2
          default: []
          selector:
            action: {}
        button_2_double_click:
          name: Double Click Action
          description: Action to perform on double click of button 2
          default: []
          selector:
            action: {}
        button_2_long_press:
          name: Long Press Action
          description: Action to perform on long press of button 2
          default: []
          selector:
            action: {}
        button_2_release:
          name: Release After Long Press Action
          description: Action to perform when button 2 is released after a long press
          default: []
          selector:
            action: {}
    
    button_3_group:
      name: "Button 3 Actions"
      icon: mdi:numeric-3-box
      collapsed: true
      input:
        button_3_single_click:
          name: Single Click Action
          description: Action to perform on single click of button 3 (for 3+ button keypads)
          default: []
          selector:
            action: {}
        button_3_double_click:
          name: Double Click Action
          description: Action to perform on double click of button 3
          default: []
          selector:
            action: {}
        button_3_long_press:
          name: Long Press Action
          description: Action to perform on long press of button 3
          default: []
          selector:
            action: {}
        button_3_release:
          name: Release After Long Press Action
          description: Action to perform when button 3 is released after a long press
          default: []
          selector:
            action: {}
    
    button_4_group:
      name: "Button 4 (Button Button) Actions"
      icon: mdi:numeric-4-box
      collapsed: true
      input:
        button_4_single_click:
          name: Single Click Action
          description: Action to perform on single click of button 4 (for 4 button keypads)
          default: []
          selector:
            action: {}
        button_4_double_click:
          name: Double Click Action
          description: Action to perform on double click of button 4
          default: []
          selector:
            action: {}
        button_4_long_press:
          name: Long Press Action
          description: Action to perform on long press of button 4
          default: []
          selector:
            action: {}
        button_4_release:
          name: Release After Long Press Action
          description: Action to perform when button 4 is released after a long press
          default: []
          selector:
            action: {}

    lower_button_group:
      name: "Lower Button (down arrow) Actions"
      icon: mdi:arrow-down-bold-box
      collapsed: true
      input: 
        button_lower_single_click:
          name: Single Click Action
          description: Action to perform on single click of lower button
          default: []
          selector:
            action: {}
        button_lower_double_click:
          name: Double Click Action
          description: Action to perform on double click of lower button
          default: []
          selector:
            action: {}
        button_lower_long_press:
          name: Long Press Action
          description: Action to perform on long press of lower button
          default: []
          selector:
            action: {}
        button_lower_release:
          name: Release After Long Press Action
          description: Action to perform when lower button is released after a long press
          default: []
          selector:
            action: {}

    raise_button_group:
      name: "Raise Button (up arrow) Actions"
      icon: mdi:arrow-up-bold-box
      collapsed: true
      input: 
        button_raise_single_click:
          name: Single Click Action
          description: Action to perform on single click of raise button
          default: []
          selector:
            action: {}
        button_raise_double_click:
          name: Double Click Action
          description: Action to perform on double click of raise button
          default: []
          selector:
            action: {}
        button_raise_long_press:
          name: Long Press Action
          description: Action to perform on long press of raise button
          default: []
          selector:
            action: {}
        button_raise_release:
          name: Release After Long Press Action
          description: Action to perform when raise button is released after a long press
          default: []
          selector:
            action: {}
        
    advanced_settings_group:
      name: "Advanced Settings"
      icon: mdi:cog
      collapsed: true
      input: 
        long_press_timeout:
          name: Long Press Timeout
          description: How long (in milliseconds) before a press becomes a long press
          default: 500
          selector:
            number:
              min: 100
              max: 2000
              step: 50
              unit_of_measurement: "ms"
        double_click_timeout:
          name: Double Click Timeout
          description: Maximum time (in milliseconds) between clicks for double-click detection
          default: 250
          selector:
            number:
              min: 100
              max: 1000
              step: 50
              unit_of_measurement: "ms"

trigger_variables:
  sunnata_keypad_device: !input sunnata_keypad

triggers:
  - trigger: event
    event_type: lutron_caseta_button_event
    event_data:
      device_id: "{{ sunnata_keypad_device }}"
    variables:
      leap_number: leap_{{ trigger.event.data.leap_button_number }}
      original_leap_button_number: "{{ trigger.event.data.leap_button_number }}"
      leap_trigger_type: "{{ trigger.event.data.action }}"

conditions: []

variables:
  long_press_timeout: !input long_press_timeout
  double_click_timeout: !input double_click_timeout
  double_click_actions:
    leap_1: !input button_1_double_click
    leap_2: !input button_2_double_click
    leap_3: !input button_3_double_click
    leap_4: !input button_4_double_click
    leap_18: !input button_lower_double_click
    leap_19: !input button_raise_double_click
  long_click_actions:
    leap_1: !input button_1_long_press
    leap_2: !input button_2_long_press
    leap_3: !input button_3_long_press
    leap_4: !input button_4_long_press
    leap_18: !input button_lower_long_press
    leap_19: !input button_raise_long_press

actions:
  - choose:
      # Path 1: Press event with double-click or long-press detection enabled
      - conditions:
          - condition: template
            value_template: >-
              {{ leap_trigger_type == 'press' and 
                 (double_click_actions[leap_number]|length > 0 or 
                  long_click_actions[leap_number]|length > 0) }}
        sequence:
          # Wait for release to detect long press
          - wait_for_trigger:
              - trigger: event
                event_type: lutron_caseta_button_event
                event_data:
                  device_id: "{{ sunnata_keypad_device }}"
                  leap_button_number: "{{ original_leap_button_number }}"
                  action: release
            timeout:
              milliseconds: "{{ long_press_timeout }}"
          - choose:
              # Long press detected (timeout expired)
              - conditions:
                  - condition: template
                    value_template: "{{ not wait.trigger }}"
                sequence:
                  - choose:
                      - conditions: ["{{ leap_number == 'leap_1' }}"]
                        sequence: !input button_1_long_press
                      - conditions: ["{{ leap_number == 'leap_2' }}"]
                        sequence: !input button_2_long_press
                      - conditions: ["{{ leap_number == 'leap_3' }}"]
                        sequence: !input button_3_long_press
                      - conditions: ["{{ leap_number == 'leap_4' }}"]
                        sequence: !input button_4_long_press
                      - conditions: ["{{ leap_number == 'leap_18' }}"]
                        sequence: !input button_lower_long_press
                      - conditions: ["{{ leap_number == 'leap_19' }}"]
                        sequence: !input button_raise_long_press
              # Not a long press, check for double-click
              - conditions:
                  - condition: template
                    value_template: "{{ double_click_actions[leap_number]|length > 0 }}"
                sequence:
                  # Wait for second press
                  - wait_for_trigger:
                      - trigger: event
                        event_type: lutron_caseta_button_event
                        event_data:
                          device_id: "{{ sunnata_keypad_device }}"
                          leap_button_number: "{{ original_leap_button_number }}"
                          action: press
                    timeout:
                      milliseconds: "{{ double_click_timeout }}"
                  - choose:
                      # Single click (no second press detected)
                      - conditions:
                          - condition: template
                            value_template: "{{ not wait.trigger }}"
                        sequence:
                          - choose:
                              - conditions: ["{{ leap_number == 'leap_1' }}"]
                                sequence: !input button_1_single_click
                              - conditions: ["{{ leap_number == 'leap_2' }}"]
                                sequence: !input button_2_single_click
                              - conditions: ["{{ leap_number == 'leap_3' }}"]
                                sequence: !input button_3_single_click
                              - conditions: ["{{ leap_number == 'leap_4' }}"]
                                sequence: !input button_4_single_click
                              - conditions: ["{{ leap_number == 'leap_18' }}"]
                                sequence: !input button_lower_single_click
                              - conditions: ["{{ leap_number == 'leap_19' }}"]
                                sequence: !input button_raise_single_click
                    # Second press detected, wait for release
                    default:
                      - wait_for_trigger:
                          - trigger: event
                            event_type: lutron_caseta_button_event
                            event_data:
                              device_id: "{{ sunnata_keypad_device }}"
                              leap_button_number: "{{ original_leap_button_number }}"
                              action: release
                        timeout:
                          milliseconds: "{{ long_press_timeout }}"
                      - choose:
                          # Long press on second click
                          - conditions:
                              - condition: template
                                value_template: "{{ not wait.trigger }}"
                            sequence:
                              - choose:
                                  - conditions: ["{{ leap_number == 'leap_1' }}"]
                                    sequence: !input button_1_long_press
                                  - conditions: ["{{ leap_number == 'leap_2' }}"]
                                    sequence: !input button_2_long_press
                                  - conditions: ["{{ leap_number == 'leap_3' }}"]
                                    sequence: !input button_3_long_press
                                  - conditions: ["{{ leap_number == 'leap_4' }}"]
                                    sequence: !input button_4_long_press
                                  - conditions: ["{{ leap_number == 'leap_18' }}"]
                                    sequence: !input button_lower_long_press
                                  - conditions: ["{{ leap_number == 'leap_19' }}"]
                                    sequence: !input button_raise_long_press
                        # Double click confirmed
                        default:
                          - choose:
                              - conditions: ["{{ leap_number == 'leap_1' }}"]
                                sequence: !input button_1_double_click
                              - conditions: ["{{ leap_number == 'leap_2' }}"]
                                sequence: !input button_2_double_click
                              - conditions: ["{{ leap_number == 'leap_3' }}"]
                                sequence: !input button_3_double_click
                              - conditions: ["{{ leap_number == 'leap_4' }}"]
                                sequence: !input button_4_double_click
                              - conditions: ["{{ leap_number == 'leap_18' }}"]
                                sequence: !input button_lower_double_click
                              - conditions: ["{{ leap_number == 'leap_19' }}"]
                                sequence: !input button_raise_double_click
            # Short press, no double-click detection needed
            default:
              - choose:
                  - conditions: ["{{ leap_number == 'leap_1' }}"]
                    sequence: !input button_1_single_click
                  - conditions: ["{{ leap_number == 'leap_2' }}"]
                    sequence: !input button_2_single_click
                  - conditions: ["{{ leap_number == 'leap_3' }}"]
                    sequence: !input button_3_single_click
                  - conditions: ["{{ leap_number == 'leap_4' }}"]
                    sequence: !input button_4_single_click
                  - conditions: ["{{ leap_number == 'leap_18' }}"]
                    sequence: !input button_lower_single_click
                  - conditions: ["{{ leap_number == 'leap_19' }}"]
                    sequence: !input button_raise_single_click
      
      # Path 2: Press event with no special detection (immediate response)
      - conditions:
          - condition: template
            value_template: "{{ leap_trigger_type == 'press' }}"
        sequence:
          - choose:
              - conditions: ["{{ leap_number == 'leap_1' }}"]
                sequence: !input button_1_single_click
              - conditions: ["{{ leap_number == 'leap_2' }}"]
                sequence: !input button_2_single_click
              - conditions: ["{{ leap_number == 'leap_3' }}"]
                sequence: !input button_3_single_click
              - conditions: ["{{ leap_number == 'leap_4' }}"]
                sequence: !input button_4_single_click
              - conditions: ["{{ leap_number == 'leap_18' }}"]
                sequence: !input button_lower_single_click
              - conditions: ["{{ leap_number == 'leap_19' }}"]
                sequence: !input button_raise_single_click
      
      # Path 3: Release event (after long press)
      - conditions:
          - condition: template
            value_template: "{{ leap_trigger_type == 'release' }}"
        sequence:
          - choose:
              - conditions: ["{{ leap_number == 'leap_1' }}"]
                sequence: !input button_1_release
              - conditions: ["{{ leap_number == 'leap_2' }}"]
                sequence: !input button_2_release
              - conditions: ["{{ leap_number == 'leap_3' }}"]
                sequence: !input button_3_release
              - conditions: ["{{ leap_number == 'leap_4' }}"]
                sequence: !input button_4_release
              - conditions: ["{{ leap_number == 'leap_18' }}"]
                sequence: !input button_lower_release
              - conditions: ["{{ leap_number == 'leap_19' }}"]
                sequence: !input button_raise_release

mode: single
